site_name: Docorvter Docs
theme:
  name: "material"
plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - section-index
  - mkdocstrings
nav:
  - Home: index.md
  - Documents: documents/
  - API Documentation: api_docs/
  - Code Reference: reference/
