apiVersion: v1
kind: Service
metadata:
  name: docorvter
  namespace: docorvter-namespace
  labels:
    app: docorvter
spec:
  type: NodePort
  selector:
    app: docorvter
  ports:
    - port: 8000
      targetPort: 8000
