version: '3.9'

services:

  django:
    image: backend_production
    container_name: backend_production_django
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: "production"
    restart: always
    env_file: ../.env/.env.production
    ports:
      - "80:8000"
    volumes:
      - ..:/backend
    command: sh -c "chmod +x ./entrypoint.sh && sh ./entrypoint.sh"

  celery:
    image: backend_production
    container_name: backend_production_celery
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file: ../.env/.env.production
    volumes:
      - ..:/backend
    command: /opt/venv/bin/celery -A src.celery worker -l info

  flower:
    image: backend_production
    container_name: backend_production_flower
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file: ../.env/.env.production
    ports:
      - "5555:5555"
    volumes:
      - ..:/backend
    command: /opt/venv/bin/celery -A src.celery flower

